services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=financas
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=financas
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: