

GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/5

###
DELETE http://localhost:3000/usuarios/2
###
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome": "MMLaiara Maiara Silva",
    "email": "MMaiara@gmail.com",
    "senha": "4321a"
}

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "MJuly Maiara Silva",
    "email": "MMjuly@gmail.com",
    "senha": "njumanow321a"
}

###
POST http://localhost:3000/usuarios/6/perfil
Content-Type: application/json

{   
    "foto": "http://google.photos/dog6.png"
}
###
GET http://localhost:3000/usuarios/5/perfil
###
DELETE  http://localhost:3000/usuarios/5/perfil
